
version: "1"
metadata:
  template: true

steps:
  - name: deploy_remote
    image: target/vela-docker:latest
    pull: always
    secrets: [ docker_username, docker_password ]
    parameters:
      registry: index.docker.io
      repo: rsscss/react-vela
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      tags: [ latest ]
      
