
version: "1"
metadata:
  template: true

steps:
  - name: deploy_remote
    image: target/vela-docker:latest
    pull: always
    secrets: [ docker_username, docker_password ]
    parameters:
      registry: index.docker.io
      repo: rsscss/react-vela
      tags: [ latest ]

secrets:
  - name: docker_username
    key: vela/rsscss/docker_username
    engine: native
    type: repo

  - name: docker_password
    key: vela/rsscss/docker_password
    engine: native
    type: repo
      
