
version: "1"
metadata:
  template: true

before_script:
    - npm install

steps:
  - name: build
    image: node:lts-alpine
    pull: always
    commands:
      - npm run build
    ruleset:
      event: [ push, pull_request ]