
version: "1"
metadata:
  template: true

steps:
  - name: install
    image: node:lts-alpine
    pull: always
    commands:
      - npm install
    ruleset:
      event: [ push, pull_request ]

  - name: build
    image: node:lts-alpine
    pull: always
    commands:
      - npm run build
    ruleset:
      event: [ push, pull_request ]
  
  - name: test
    image: node:lts-alpine
    pull: always
    commands:
      - npm test
    ruleset:
      event: [ push, pull_request ]

  - name: deploy
    image: target/vela-docker:latest
    pull: always
    parameters:
      registry: index.docker.io
      repo: rsscss/react-vela
      tags: [ latest ]
-username: docker_username
-password: docker_password
