
version: "1"
metadata:
  template: true

steps:
  - name: install
    image: node:lts-alpine
    pull: always
    commands:
      - npm install
    ruleset:
      event: [ push, pull_request ]

  - name: build
    image: node:lts-alpine
    pull: always
    commands:
      - npm run build
    ruleset:
      event: [ push, pull_request ]
  
  - name: test
    image: node:lts-alpine
    pull: always
    commands:
      - npm test
    ruleset:
      event: [ push, pull_request ]

  - name: deploy
    image: docker:latest
    pull: always
    secrets: [ docker_username, docker_password, registry ]
    commands:
      - echo docker_password | docker login -u docker_username -p docker_password registry
      - docker build --pull -t rsscss/react-vela:latest .
      - docker push rsscss/react-vela:latest
